version: '3.1'
services:
    rabbitmq:
      build:
        context: ./files/dependencies/rabbitmq
      image: rmq
      
      ports:
        - "5672:5672"
        - "15672:15672"
      
    messagesender:
      build:
        context: ./
      image: messagesender
      network_mode: "host"
      depends_on: 
        - rabbitmq
      ports: 
        - "8080:8080"
